/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : JIPsoft (Joona I Palaste)
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_Message                             0
#define GD_Lives                               1
#define GD_Time                                2
#define GD_Diamonds                            3
#define GD_Blue                                4
#define GD_Green                               5
#define GD_Red                                 6
#define GD_Level                               7
#define GD_Score                               8

#define GDX_Message                            0
#define GDX_Lives                              1
#define GDX_Time                               2
#define GDX_Diamonds                           3
#define GDX_Blue                               4
#define GDX_Green                              5
#define GDX_Red                                6
#define GDX_Level                              7
#define GDX_Score                              8

#define MagicMiner_CNT 9

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern APTR                  VisualInfo;
extern struct Window        *MagicMinerWnd;
extern struct Gadget        *MagicMinerGList;
extern struct Menu          *MagicMinerMenus;
extern struct IntuiMessage   MagicMinerMsg;
extern struct Gadget        *MagicMinerGadgets[9];
extern UWORD                 MagicMinerLeft;
extern UWORD                 MagicMinerTop;
extern UWORD                 MagicMinerWidth;
extern UWORD                 MagicMinerHeight;
extern UBYTE                *MagicMinerWdt;
extern struct TextAttr       topaz8;
extern struct IntuiText      MagicMinerIText[];
extern struct NewMenu        MagicMinerNewMenu[];
extern UWORD                 MagicMinerGTypes[];
extern struct NewGadget      MagicMinerNGad[];
extern ULONG                 MagicMinerGTags[];
extern struct ColorSpec      ScreenColors[];
extern UWORD                 DriPens[];

extern int MagicMinerLoad( void );
extern int MagicMinerAbout( void );
extern int MagicMinerQuit( void );

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void MagicMinerRender( void );
extern int HandleMagicMinerIDCMP( void );
extern int MagicMinerActiveWindow();
extern int MagicMinerInActiveWindow();
extern int MagicMinerRawKey();
extern int MagicMinerIntuiTicks();
extern int OpenMagicMinerWindow( void );
extern void CloseMagicMinerWindow( void );

#define UP 1
#define RIGHT 8
#define DOWN 2
#define LEFT 4
#define FIRE 0x4000
#define LIVES 0
#define TIME 1
#define DIAMONDS 2
#define BLUE 3
#define GREEN 4
#define RED 5
#define LEVEL 6
#define SCORE 7
#define PLAYER 0
#define ENEMY 1

struct level
{
    UBYTE number;                       /* The number of this level */
    UBYTE plrx;                         /* Initial X coordinate for player */
    UBYTE plry;                         /* Initial Y coordinate for player */
    UBYTE nmex;                         /* Initial X coordinate for enemy */
    UBYTE nmey;                         /* Initial Y coordinate for enemy */
    UBYTE flags;                        /* Difficulty, background and gravity */
    UWORD diamonds;                     /* How many diamonds are needed */
    UWORD time;                         /* How many seconds we have time */
    WORD next;                          /* Array index for the next level */
    WORD prev;                          /* Array index for the previous level */
    UBYTE *name;                        /* Pointer to level name */
    UBYTE *data;                        /* Pointer to actual level data */
    UBYTE *special;                     /* Pointer to map of special blocks */
    UBYTE *specialdata;                 /* Pointer to array of special datas */
};
